---
- name: "Restart buildbot-worker"
  ansible.builtin.include_tasks: "{{ item }}"
  with_first_found:
    - files: "{{ __buildbot_worker_os_search_list }}"
      paths: "{{ role_path }}/handlers/restart"
