---
- name: "Create buildbot base directory"
  become: yes
  file:
    state: directory
    path: "{{ buildbot_worker_basedir }}"
    owner: "{{ buildbot_worker_user }}"
    group: "{{ buildbot_worker_group }}"
    mode: "0755"

- name: "Create buildbot worker"
  become: yes
  become_method: sudo
  become_user: buildbot
  command:
    cmd: >
      {{ buildbot_worker_bin }} create-worker {{ buildbot_worker_basedir }}
      {{ buildbot_master_host }}:{{ buildbot_master_port }}
      {{ buildbot_worker_name }} {{ buildbot_worker_password }}
    creates: "{{ buildbot_worker_basedir }}/buildbot.tac"

- name: "Update buildbot worker configuration"
  become: yes
  become_method: sudo
  become_user: buildbot
  lineinfile:
    path: "{{ buildbot_worker_basedir }}/buildbot.tac"
    regexp: "^{{ config_item.key }} ="
    line: "{{ config_item.key }} = {{ config_item.value }}"
  with_dict:
    buildmaster_host: "'{{ buildbot_master_host }}'"
    basedir: "'{{ buildbot_worker_basedir }}'"
    port: "{{ buildbot_master_port }}"
    workername: "'{{ buildbot_worker_name }}'"
    passwd: "'{{ buildbot_worker_password }}'"
  loop_control:
    loop_var: config_item
    label: "key: {{ config_item.key }}, value: {{ (config_item.key == 'passwd') | ternary('********', config_item.value) }}"

- name: "Create buildbot worker info directory."
  become: yes
  file:
    state: directory
    path: "{{ buildbot_worker_basedir }}/info"
    owner: "{{ buildbot_worker_user }}"
    group: "{{ buildbot_worker_group }}"
    mode: "0755"

- name: "Update buildbot worker info files."
  become: yes
  template:
    src: "info-{{ info_item }}.j2"
    dest: "{{ buildbot_worker_basedir }}/info/{{ info_item }}"
    owner: "{{ buildbot_worker_user }}"
    group: "{{ buildbot_worker_group }}"
    mode: "0644"
  loop:
    - "host"
    - "admin"
    - "access_uri"
  loop_control:
    loop_var: info_item
