---
- name: "Fedora-31: Install buildbot worker systemd unit file"
  become: yes
  vars:
    buildbot_worker_bin: /usr/bin/buildbot-worker
  template:
    src: buildbot-worker.service.j2
    dest: /etc/systemd/system/buildbot-worker.service
    owner: root
    group: root
    mode: 0644
  notify: "Restart service"
  register: unitfile
  tags: root

- name: "Fedora-31: Set service name"
  set_fact:
    buildbot_worker_service: buildbot-worker

- name: "Fedora-31: Start buildbot worker service"
  become: yes
  systemd:
    name: "{{ buildbot_worker_service }}"
    daemon_reload: yes
    enabled: yes
    state: started
  tags: root
