---
# Honor the old 'solaris_cc' variable for backward compatibility.
# New playbooks should specify the buildbot_worker_environment dict.
- name: "Solaris 11.4: Check for deprecated solaris_cc variable."
  debug:
    msg: "Role variable solaris_cc is deprecated; use buildbot_worker_environment"
  when: solaris_cc is defined

- name: "Solaris 11.4: Use deprecated solaris_cc variable for compatibility."
  set_fact:
    buildbot_worker_environment:
      SOLARISCC: "{{ solaris_cc }}"
  when:
    - buildbot_worker_environment is undefined
    - solaris_cc is defined

- name: "Solaris 11.4: Upload SMF manifest"
  become: yes
  template:
    src: buildbot-worker.xml.j2
    dest: /root/buildbot-worker.xml
    owner: root
    group: root
    mode: 0644
  register: buildbot_worker_manifest
  tags: root

- name: "Solaris 11.4: Set service name"
  set_fact:
    buildbot_worker_service: buildbot-worker

# This also enables and starts the smf service.
- name: "Solaris 11.4: Import SMF manifest"
  become: yes
  command: svccfg import /root/buildbot-worker.xml
  when: buildbot_worker_manifest.changed
  tags: root
