---
# Legacy init.d settings file.
- name: "Ubuntu: Install buildbot worker settings"
  become: yes
  ansible.builtin.template:
    src: buildbot-worker.debian.j2
    dest: /etc/default/buildbot-worker
    owner: root
    group: root
    mode: 0644
  register: buildbot_worker_settings_results
  notify: "Restart buildbot-worker"

- name: "Ubuntu: Start buildbot worker service"
  become: yes
  ansible.builtin.systemd:
    name: "buildbot-worker@{{ buildbot_project }}"
    enabled: yes
    state: started
  when: not buildbot_worker_settings_results.changed
