---
- name: "CentOS-7: Add EPEL repository"
  become: yes
  yum:
    state: present
    name: epel-release
    update_cache: yes
  tags: root

# A c compiler is required to build the twisted modules.
- name: "CentOS-7: Install packages"
  become: yes
  yum:
    state: present
    name:
     - python3
     - make
     - gcc
  tags: root

# Install the buildbot-worker in a python virtualenv.  A recent pip is required
# to workaround the new rust requirements imposed by the crypto team (thanks for
# that).  This is not easy to do with the pip module, so we fallback to using a
# series of shell commands.  The command 'creates' arg is specified for
# idempotentcy.
- name: "CentOS-7: Create python virtualenv for buildbot-worker"
  become: yes
  command:
    cmd: /usr/bin/python3 -m venv /opt/buildbot-worker
    creates: /opt/buildbot-worker
  tags: root

- name: "CentOS-7: Upgrade python pip in the buildbot-worker virtualenv"
  become: yes
  command:
    cmd: /opt/buildbot-worker/bin/pip3 install -U pip
    # Upgrade pip if we are going to install the buildbot packages.
    creates: /opt/buildbot-worker/lib/python3.6/site-packages/buildbot_worker
  tags: root

- name: "CentOS-7: Install buildbot-worker"
  become: yes
  command:
    cmd: /opt/buildbot-worker/bin/pip3 install buildbot-worker==3.11.9
    creates: /opt/buildbot-worker/lib/python3.6/site-packages/buildbot_worker
  tags: root

- name: "CentOS-7: Create buildbot-worker symlink"
  become: yes
  file:
    state: link
    src: /opt/buildbot-worker/bin/buildbot-worker
    path: "{{ buildbot_worker_bin }}"
  tags: root
