---
- name: "MacOS: Create python virtual env"
  become: yes
  pip:
    name: pip
    state: latest
    virtualenv: /opt/buildbot-worker
    virtualenv_command: /usr/bin/python3 -m venv
  tags: root

- name: "MacOS: Install buildbot worker"
  become: yes
  pip:
    name: buildbot-worker
    virtualenv: /opt/buildbot-worker
  tags: root

- name: "MacOS: Create command symlink"
  become: yes
  file:
    state: link
    src: /opt/buildbot-worker/bin/buildbot-worker
    path: "{{ buildbot_worker_bin }}"
  tags: root
