---
# Install the build requirements for python extensions to be built by pip
# install.  The Python cryptography package requires a rust compiler, since
# pre-built binaries are not available for Solaris.
- name: "Solaris 11.4: Ensure required packages are installed."
  become: yes
  pkg5:
    state: present
    name:
      - runtime/python-37
      - python/virtualenv
      - developer/build/pkg-config
      - developer/rust/rustc
      - developer/rust/cargo
      - library/security/openssl-11
  tags: root

# The Python cryptography package requires openssl 1.1 or greater. By default
# both the 1.0 and 1.1 versions are installed, and the package mediator is
# used to select the needed version.
- name: "Solaris 11.4: Query openssl version."
  command:
    cmd: pkg mediator -H -F json openssl
  changed_when: false
  register: pkg_mediator_results

- name: "Solaris 11.4: Select openssl 1.1."
  become: yes
  command:
    cmd: pkg set-mediator -I default@1.1 openssl
  when: (pkg_mediator_results.stdout | from_json)[0].implementation == 'default@1.0'
  tags: root

# Create the virtual env and upgrade pip to the most recent version.
- name: "Solaris 11.4: Create the python virtualenv for the buildbot worker."
  become: yes
  pip:
    state: latest
    name: pip
    virtualenv: /opt/buildbot-worker
    virtualenv_python: /usr/bin/python3
  tags: root

- name: "Solaris 11.4: Install buildbot worker"
  become: yes
  pip:
    virtualenv: /opt/buildbot-worker
    name: buildbot-worker
  environment:
    PKG_CONFIG_PATH: /usr/lib/64/pkgconfig
  tags: root

- name: "Solaris 11.4: Set buildbot-worker path."
  set_fact:
    buildbot_worker_bin: /usr/bin/buildbot-worker

- name: "Solaris 11.4: Create buildbot-worker symlink."
  become: yes
  file:
    state: link
    src: /opt/buildbot-worker/bin/buildbot-worker
    path: "{{ buildbot_worker_bin }}"
  tags: root
