---
# The ansible_user must be a member of the Administators group.
- name: "Windows: Restart Buildbot service."
  ansible.windows.win_service:
    name: BuildBot
    start_mode: auto
    state: restarted
