---
- name: "Buildbot worker required variables check."
  ansible.builtin.assert:
    that:
      - buildbot_project is defined
      - buildbot_master_host is defined
      - buildbot_master_port is defined
      - buildbot_worker_name is defined
      - buildbot_worker_admin is defined
      - buildbot_worker_password is defined
      - buildbot_worker_password | length > 0

- name: "Trace OS search list."
  debug:
    var: __buildbot_worker_os_search_list

- name: "Set OS specific variables"
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files: "{{ __buildbot_worker_os_search_list }}"
      paths: "{{ role_path }}/vars/os"

- name: "Stage 1: Install buildbot-worker package."
  ansible.builtin.include_tasks: "{{ item }}"
  with_first_found:
    - files: "{{ __buildbot_worker_os_search_list }}"
      paths: "{{ role_path }}/tasks/install"

- name: "Stage 2: Create buildbot user account."
  ansible.builtin.include_tasks: "{{ item }}"
  with_first_found:
    - files: "{{ __buildbot_worker_os_search_list }}"
      paths: "{{ role_path }}/tasks/user"

- name: "Stage 3: Configure buildbot-worker instance."
  ansible.builtin.include_tasks: "{{ item }}"
  with_first_found:
    - files: "{{ __buildbot_worker_os_search_list }}"
      paths: "{{ role_path }}/tasks/setup"

- name: "Stage 4: Setup buildbot-worker service."
  ansible.builtin.include_tasks: "{{ item }}"
  with_first_found:
    - files: "{{ __buildbot_worker_os_search_list }}"
      paths: "{{ role_path }}/tasks/service"
