---
- name: "Create the buildbot master instance."
  command:
    cmd: "{{ buildbot_master_buildbot_command }} create-master {{ buildbot_master_basedir }}"
    creates: "{{ buildbot_master_basedir }}/buildbot.tac"
  tags:
    - configure

- name: "Install the buildbot master configuration."
  template:
    src: "{{ item }}"
    dest: "{{ buildbot_master_basedir }}/{{ item | basename | regex_replace('\\.j2$', '') }}"
  loop: "{{ buildbot_master_config_templates }}"
  # Note: We restart on configuration change for now since reloading
  #       has been found to break the gerrit integration in the past.
  notify: "restart buildbot master {{ buildbot_master_have_sudo | ternary('service', 'instance') }}"
  tags:
    - configure

- name: "Verify the buildbot master configuration."
  command:
    cmd: "{{ buildbot_master_buildbot_command }} checkconfig"
    chdir: "{{ buildbot_master_basedir }}"
  # Always run, even in --check mode.
  check_mode: no
  changed_when: false
  register: checkconfig_results
  tags:
    - configure

#- debug:
#    var: checkconfig_results
