---
dependency:
  name: galaxy

platforms:
  - name: m-bot
    box: ${BOX:-generic/debian11}
    groups:
      - openafs_buildbot_workers

provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        ansible_shell_allow_world_readable_temp: true
    host_vars:
      m-bot:
        buildbot_project: test
        buildbot_worker_name: testbot
        buildbot_worker_password: secret
        buildbot_worker_admin: "tycobb@yoyodyne.com"

verifier:
  name: ansible
